---
# Reconciler app configuration

#######################################################################
# General settings

# The organisation name is the charity name.
organisation_name: "My Organisation"

# The data date start is the date from which information should be
# synchronised into the local system to effect reconciliation between
# the systems.
data_date_start: "2025-04-01"

# The Xero donation account prefixes are the patterns matching the
# beginning of any account codes that record donation income.
donation_account_prefixes:
  - "53"                                                                  
  - "55"                                                                  
  - "57"

#######################################################################
# Web server settings
web:
  listen_address: "localhost:8080"
  xero_oauth2_callback: "/xero/callback"
  salesforce_oauth2_callback: "/salesforce/callback"

#######################################################################
# Xero API settings
#
# These settings set out the OAuth2 connection settings to the remote
# platform. PKCE code verification is required
xero:
  client_id: "XERO_CLIENT_ID"
  client_secret: "" # should not be provided for Xero PKCE connections.

#######################################################################
# Salesforce API settings
#
# These settings set out the OAuth2 connection settings to the remote
# platform. PKCE code verification is required.
#
# The SOQL donation retrieval query is specified, together with the
# object and field name to target in distributed foreign key (DFK)
# updates.
salesforce:
  login_domain: "test.salesforce.com"
  client_id: "SALESFORCE_CONSUMER_KEY"
  client_secret: "SALESFORCE_CONSUMER_SECRET"

  # The SOQL query to execute. 
  # Do not specify a "WHERE" clause. This is added automatically at
  # system start. Adding a "WHERE" clause will cause startup to fail.
  query: >-
    SELECT
      Id, Name, Amount, CloseDate, LastModifiedDate, Payout_Reference__c,
      StageName, RecordType.Name, Account.Name,
      CreatedBy.Name, CreatedDate, LastModifiedBy.Name
    FROM Opportunity

  # Optional field mappings from the SOQL query to show in the UI.
  field_mappings:
    StageName: Stage
    Account.Name: Account
    CreatedBy.Name: CreatedBy
    LastModifiedBy.Name: ModifiedBy

  # Target object and field for Distributed Foreign Key (DFK) updates.
  # Note that the linking_object.linking_field_name is the only field
  # that is updated in this system.
  linking_object: "Opportunity"
  linking_field_name: "Payout_Reference__c"

